/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 */

#ifndef _ForeseeIndication_H_
#define _ForeseeIndication_H_

#include "asn_application.h"
#include "NativeInteger.h"
#include "DeltaTimeMilliSecondPositive.h"
#include "LongitudinalAcceleration.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ForeseeIndication */
typedef struct ForeseeIndication {
    LongitudinalAcceleration_t acceleration;
    DeltaTimeMilliSecondPositive_t duration;
    
    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} ForeseeIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ForeseeIndication;
extern asn_SEQUENCE_specifics_t asn_SPC_ForeseeIndication_specs_1;
extern asn_TYPE_member_t asn_MBR_ForeseeIndication_1[2];

#ifdef __cplusplus
}
#endif

#endif /* _ForeseeIndication_H_ */