/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 */

#include "ForeseeIndication.h"

asn_TYPE_member_t asn_MBR_ForeseeIndication_1[] = {
    { ATF_NOFLAGS, 0, offsetof(struct ForeseeIndication, acceleration),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_NativeInteger,
        0,
        { 0, 0, 0 },
        0, 0, /* No default value */
        "acceleration"
        },
    { ATF_NOFLAGS, 0, offsetof(struct ForeseeIndication, duration),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
        -1,    /* IMPLICIT tag at current level */
        &asn_DEF_DeltaTimeMilliSecondPositive,
        0,
        { 0, 0, 0 },
        0, 0, /* No default value */
        "duration"
        },
};

static const ber_tlv_tag_t asn_DEF_ForeseeIndication_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};

static const asn_TYPE_tag2member_t asn_MAP_ForeseeIndication_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* acceleration */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }  /* duration */
};

asn_SEQUENCE_specifics_t asn_SPC_ForeseeIndication_specs_1 = {
    sizeof(struct ForeseeIndication),
    offsetof(struct ForeseeIndication, _asn_ctx),
    asn_MAP_ForeseeIndication_tag2el_1,
    2,  /* Count of tags in the map */
    0, 0, 0,    /* Optional elements (none) */
    -1, /* First extension addition */
};

asn_TYPE_descriptor_t asn_DEF_ForeseeIndication = {
    "ForeseeIndication",
    "ForeseeIndication",
    &asn_OP_SEQUENCE,
    asn_DEF_ForeseeIndication_tags_1,
    sizeof(asn_DEF_ForeseeIndication_tags_1)
        /sizeof(asn_DEF_ForeseeIndication_tags_1[0]),
    asn_DEF_ForeseeIndication_tags_1,
    sizeof(asn_DEF_ForeseeIndication_tags_1)
        /sizeof(asn_DEF_ForeseeIndication_tags_1[0]),
    { 
#if !defined(ASN_DISABLE_OER_SUPPORT)
        0, 
#endif
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
        0, 
#endif
#if !defined(ASN_DISABLE_JER_SUPPORT)
        0, 
#endif
        SEQUENCE_constraint 
    },
    asn_MBR_ForeseeIndication_1,
    2,  /* Elements count */
    &asn_SPC_ForeseeIndication_specs_1
};