/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 *  found in "preprocessed_temp/MCM.asn"
 * Modified: added acceleration and durationDeltaTime as OPTIONAL fields
 */

#include "Submanoeuvre.h"

asn_TYPE_member_t asn_MBR_Submanoeuvre_1[] = {
    /* submanoeuvreId: mandatory, index 0, tag 0 */
    { ATF_NOFLAGS, 0, offsetof(struct Submanoeuvre, submanoeuvreId),
     (ASN_TAG_CLASS_CONTEXT | (0 << 2)),
     -1,	/* IMPLICIT tag at current level */
     &asn_DEF_Identifier1B,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_JER_SUPPORT)
         0,
#endif
         0
     },
     0, 0,
     "submanoeuvreId"
    },
    /* acceleration: OPTIONAL, index 1, tag 1 — 3 optional members follow */
    { ATF_POINTER, 3, offsetof(struct Submanoeuvre, acceleration),
     (ASN_TAG_CLASS_CONTEXT | (1 << 2)),
     -1,	/* IMPLICIT tag at current level */
     &asn_DEF_LongitudinalAcceleration,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_JER_SUPPORT)
         0,
#endif
         0
     },
     0, 0,
     "acceleration"
    },
    /* durationDeltaTime: OPTIONAL, index 2, tag 2 — 2 optional members follow */
    { ATF_POINTER, 2, offsetof(struct Submanoeuvre, durationDeltaTime),
     (ASN_TAG_CLASS_CONTEXT | (2 << 2)),
     -1,	/* IMPLICIT tag at current level */
     &asn_DEF_DeltaTimeMilliSecondPositive,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_JER_SUPPORT)
         0,
#endif
         0
     },
     0, 0,
     "durationDeltaTime"
    },
    /* advisedTrajectory: OPTIONAL, index 3, tag 3 — 1 optional member follows */
    { ATF_POINTER, 1, offsetof(struct Submanoeuvre, advisedTrajectory),
     (ASN_TAG_CLASS_CONTEXT | (3 << 2)),
     -1,	/* IMPLICIT tag at current level */
     &asn_DEF_Trajectory,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_JER_SUPPORT)
         0,
#endif
         0
     },
     0, 0,
     "advisedTrajectory"
    },
    /* advisedTargetRoadResource: OPTIONAL, index 4, tag 4 — 0 optional members follow */
    { ATF_POINTER, 0, offsetof(struct Submanoeuvre, advisedTargetRoadResource),
     (ASN_TAG_CLASS_CONTEXT | (4 << 2)),
     -1,	/* IMPLICIT tag at current level */
     &asn_DEF_AdvisedTrrContainer,
     0,
     {
#if !defined(ASN_DISABLE_OER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
         0,
#endif
#if !defined(ASN_DISABLE_JER_SUPPORT)
         0,
#endif
         0
     },
     0, 0,
     "advisedTargetRoadResource"
    },
};

/* Optional members: acceleration(1), durationDeltaTime(2), advisedTrajectory(3), advisedTargetRoadResource(4) */
static const int asn_MAP_Submanoeuvre_oms_1[] = { 1, 2, 3, 4 };

static const ber_tlv_tag_t asn_DEF_Submanoeuvre_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};

/* tag2el: 5 entries, tags 0-4 */
static const asn_TYPE_tag2member_t asn_MAP_Submanoeuvre_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* submanoeuvreId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* acceleration */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* durationDeltaTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* advisedTrajectory */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }  /* advisedTargetRoadResource */
};

asn_SEQUENCE_specifics_t asn_SPC_Submanoeuvre_specs_1 = {
    sizeof(struct Submanoeuvre),
    offsetof(struct Submanoeuvre, _asn_ctx),
    asn_MAP_Submanoeuvre_tag2el_1,
    5,	/* Count of tags in the map */
    asn_MAP_Submanoeuvre_oms_1,	/* Optional members */
    4, 0,	/* 4 optional members, 0 extension additions */
    -1,	/* First extension addition */
};

asn_TYPE_descriptor_t asn_DEF_Submanoeuvre = {
    "Submanoeuvre",
    "Submanoeuvre",
    &asn_OP_SEQUENCE,
    asn_DEF_Submanoeuvre_tags_1,
    sizeof(asn_DEF_Submanoeuvre_tags_1)
        /sizeof(asn_DEF_Submanoeuvre_tags_1[0]),
    asn_DEF_Submanoeuvre_tags_1,
    sizeof(asn_DEF_Submanoeuvre_tags_1)
        /sizeof(asn_DEF_Submanoeuvre_tags_1[0]),
    {
#if !defined(ASN_DISABLE_OER_SUPPORT)
        0,
#endif
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
        0,
#endif
#if !defined(ASN_DISABLE_JER_SUPPORT)
        0,
#endif
        SEQUENCE_constraint
    },
    asn_MBR_Submanoeuvre_1,
    5,	/* Elements count */
    &asn_SPC_Submanoeuvre_specs_1
};